'''
Joe Walter

difficulty: 5%
run time:   0:00
answer:     1533776805

	***

045 Triangular Pentagonal And Hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	1, 3,  6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

def T(n):
	return n*(n+1) // 2

def P(n):
	return n*(3*n-1) // 2

def H(n):
	return n*(2*n-1)

t_index = 286
p_index = 165
h_index = 144

t_val = T(t_index)
p_val = P(p_index)
h_val = H(h_index)

while t_val != p_val or p_val != h_val:
	if t_val < p_val:
		t_index += 1
		t_val = T(t_index)
	if p_val < h_val:
		p_index += 1
		p_val = P(p_index)
	if h_val < t_val:
		h_index += 1
		h_val = H(h_index)

print(t_val)
